site_name: The Internals of Kafka Streams
site_url: https://books.japila.pl/kafka-streams-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Kafka Streams

repo_name: kafka-streams-internals
repo_url: https://github.com/japila-books/kafka-streams-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags:
  #     tags_file: tags.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Kafka Streams
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
  kafka:
    version: 3.0.0
    github: https://github.com/apache/kafka/tree/3.0.0
  scala:
    short_version: 2.13
    api: https://www.scala-lang.org/api/2.13.6
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.13
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - KafkaStreams: KafkaStreams.md
    - StreamsConfig: StreamsConfig.md
    - StreamsPartitionAssignor: StreamsPartitionAssignor.md
    - Topology: Topology.md
    - TopologyTestDriver: TopologyTestDriver.md
  - Processor API:
    - AbstractTask: processor/AbstractTask.md
    - ActiveTaskCreator: processor/ActiveTaskCreator.md
    - InternalTopologyBuilder: processor/InternalTopologyBuilder.md
    - NodeFactory: processor/NodeFactory.md
    - ProcessorStateManager: processor/ProcessorStateManager.md
    - ProcessorTopology: processor/ProcessorTopology.md
    - SourceNodeFactory: processor/SourceNodeFactory.md
    - StandbyTask: processor/StandbyTask.md
    - StandbyTaskCreator: processor/StandbyTaskCreator.md
    - StateDirectory: processor/StateDirectory.md
    - StreamTask: processor/StreamTask.md
    - StreamThread: processor/StreamThread.md
    - Task: processor/Task.md
    - TaskManager: processor/TaskManager.md
    - Tasks: processor/Tasks.md
  - State:
    - QueryableStoreProvider: state/QueryableStoreProvider.md
    - StoreBuilder: state/StoreBuilder.md
    - StreamThreadStateStoreProvider: state/StreamThreadStateStoreProvider.md
